*BOUNDARY_SPC_SET
$#    nsid       cid      dofx      dofy      dofz     dofrx     dofry     dofrz
         2         0         1         0         0         0         0         0
$#    nsid       cid      dofx      dofy      dofz     dofrx     dofry     dofrz
         3         0         0         1         0         0         0         0
$#    nsid       cid      dofx      dofy      dofz     dofrx     dofry     dofrz
         4         0         0         0         1         0         0         0
