*SECTION_SOLID
$#   secid    elform       aet   
         1       101         0
$#     nip     nxdof      ihgf      itaj       lmc      nhsv    
         0         0         0         0         2         6
$#      p1        p2        p3        p4        p5        p6        p7        p8
     100.0       0.3       0.0       0.0       0.0       0.0       0.0         8
*MAT_ELASTIC
$#     mid        ro         e        pr        da        db  not used        
         1   7.80E-9     100.0       0.3       0.0       0.0       0.0
